# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc72193dd74cf268edc77c2c8ed147f36203915ab2906fa599d5ede9d96dcb5b109aa3503c6b2595fa594b4c03029e4bbe3e8cc4b61fb4f2b6c7ab5a16c7ff2

test:
  secret_key_base: 072df10bca612ae53a15c19c8693298120d8471d4aa6161d7ef4612014034b53408b13e685921ebac784229e08ef5f63b1cbf7abba29a6645dd535a4c3b9cfc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
